// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authn.proto

package grpc_authn_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Principal struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" bson:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty" bson:"Username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty" bson:"Password,omitempty"`
	Roles                []string `protobuf:"bytes,4,rep,name=Roles,proto3" json:"Roles,omitempty" bson:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Principal) Reset()         { *m = Principal{} }
func (m *Principal) String() string { return proto.CompactTextString(m) }
func (*Principal) ProtoMessage()    {}
func (*Principal) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{0}
}
func (m *Principal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Principal.Unmarshal(m, b)
}
func (m *Principal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Principal.Marshal(b, m, deterministic)
}
func (dst *Principal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Principal.Merge(dst, src)
}
func (m *Principal) XXX_Size() int {
	return xxx_messageInfo_Principal.Size(m)
}
func (m *Principal) XXX_DiscardUnknown() {
	xxx_messageInfo_Principal.DiscardUnknown(m)
}

var xxx_messageInfo_Principal proto.InternalMessageInfo

func (m *Principal) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Principal) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Principal) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Principal) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type Role struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" bson:"Name,omitempty"`
	Permissions          []string `protobuf:"bytes,2,rep,name=Permissions,proto3" json:"Permissions,omitempty" bson:"Permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{1}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (dst *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(dst, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type NotifyMFARequest struct {
	Principal            *Principal `protobuf:"bytes,1,opt,name=Principal,proto3" json:"Principal,omitempty" bson:"Principal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NotifyMFARequest) Reset()         { *m = NotifyMFARequest{} }
func (m *NotifyMFARequest) String() string { return proto.CompactTextString(m) }
func (*NotifyMFARequest) ProtoMessage()    {}
func (*NotifyMFARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{2}
}
func (m *NotifyMFARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMFARequest.Unmarshal(m, b)
}
func (m *NotifyMFARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMFARequest.Marshal(b, m, deterministic)
}
func (dst *NotifyMFARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMFARequest.Merge(dst, src)
}
func (m *NotifyMFARequest) XXX_Size() int {
	return xxx_messageInfo_NotifyMFARequest.Size(m)
}
func (m *NotifyMFARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMFARequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMFARequest proto.InternalMessageInfo

func (m *NotifyMFARequest) GetPrincipal() *Principal {
	if m != nil {
		return m.Principal
	}
	return nil
}

type NotifyMFAResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyMFAResponse) Reset()         { *m = NotifyMFAResponse{} }
func (m *NotifyMFAResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyMFAResponse) ProtoMessage()    {}
func (*NotifyMFAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{3}
}
func (m *NotifyMFAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMFAResponse.Unmarshal(m, b)
}
func (m *NotifyMFAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMFAResponse.Marshal(b, m, deterministic)
}
func (dst *NotifyMFAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMFAResponse.Merge(dst, src)
}
func (m *NotifyMFAResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyMFAResponse.Size(m)
}
func (m *NotifyMFAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMFAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMFAResponse proto.InternalMessageInfo

type AuthenticateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty" bson:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty" bson:"Password,omitempty"`
	MFA                  string   `protobuf:"bytes,3,opt,name=MFA,proto3" json:"MFA,omitempty" bson:"MFA,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{4}
}
func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(dst, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthenticateRequest) GetMFA() string {
	if m != nil {
		return m.MFA
	}
	return ""
}

type AuthenticateResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty" bson:"Token,omitempty"`
	Roles                []string `protobuf:"bytes,2,rep,name=Roles,proto3" json:"Roles,omitempty" bson:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{5}
}
func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(dst, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthenticateResponse) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type GetPrincipalPermissionsRequest struct {
	Principal            *Principal `protobuf:"bytes,1,opt,name=Principal,proto3" json:"Principal,omitempty" bson:"Principal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetPrincipalPermissionsRequest) Reset()         { *m = GetPrincipalPermissionsRequest{} }
func (m *GetPrincipalPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPrincipalPermissionsRequest) ProtoMessage()    {}
func (*GetPrincipalPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{6}
}
func (m *GetPrincipalPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrincipalPermissionsRequest.Unmarshal(m, b)
}
func (m *GetPrincipalPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrincipalPermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *GetPrincipalPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrincipalPermissionsRequest.Merge(dst, src)
}
func (m *GetPrincipalPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPrincipalPermissionsRequest.Size(m)
}
func (m *GetPrincipalPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrincipalPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrincipalPermissionsRequest proto.InternalMessageInfo

func (m *GetPrincipalPermissionsRequest) GetPrincipal() *Principal {
	if m != nil {
		return m.Principal
	}
	return nil
}

type GetPrincipalPermissionsResponse struct {
	Roles                []*Role  `protobuf:"bytes,1,rep,name=Roles,proto3" json:"Roles,omitempty" bson:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPrincipalPermissionsResponse) Reset()         { *m = GetPrincipalPermissionsResponse{} }
func (m *GetPrincipalPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPrincipalPermissionsResponse) ProtoMessage()    {}
func (*GetPrincipalPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{7}
}
func (m *GetPrincipalPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrincipalPermissionsResponse.Unmarshal(m, b)
}
func (m *GetPrincipalPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrincipalPermissionsResponse.Marshal(b, m, deterministic)
}
func (dst *GetPrincipalPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrincipalPermissionsResponse.Merge(dst, src)
}
func (m *GetPrincipalPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPrincipalPermissionsResponse.Size(m)
}
func (m *GetPrincipalPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrincipalPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrincipalPermissionsResponse proto.InternalMessageInfo

func (m *GetPrincipalPermissionsResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type AddDomainRealmRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDomainRealmRequest) Reset()         { *m = AddDomainRealmRequest{} }
func (m *AddDomainRealmRequest) String() string { return proto.CompactTextString(m) }
func (*AddDomainRealmRequest) ProtoMessage()    {}
func (*AddDomainRealmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{8}
}
func (m *AddDomainRealmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDomainRealmRequest.Unmarshal(m, b)
}
func (m *AddDomainRealmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDomainRealmRequest.Marshal(b, m, deterministic)
}
func (dst *AddDomainRealmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDomainRealmRequest.Merge(dst, src)
}
func (m *AddDomainRealmRequest) XXX_Size() int {
	return xxx_messageInfo_AddDomainRealmRequest.Size(m)
}
func (m *AddDomainRealmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDomainRealmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDomainRealmRequest proto.InternalMessageInfo

type AddDomainRealmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDomainRealmResponse) Reset()         { *m = AddDomainRealmResponse{} }
func (m *AddDomainRealmResponse) String() string { return proto.CompactTextString(m) }
func (*AddDomainRealmResponse) ProtoMessage()    {}
func (*AddDomainRealmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{9}
}
func (m *AddDomainRealmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDomainRealmResponse.Unmarshal(m, b)
}
func (m *AddDomainRealmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDomainRealmResponse.Marshal(b, m, deterministic)
}
func (dst *AddDomainRealmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDomainRealmResponse.Merge(dst, src)
}
func (m *AddDomainRealmResponse) XXX_Size() int {
	return xxx_messageInfo_AddDomainRealmResponse.Size(m)
}
func (m *AddDomainRealmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDomainRealmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDomainRealmResponse proto.InternalMessageInfo

type GetRolesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesRequest) Reset()         { *m = GetRolesRequest{} }
func (m *GetRolesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRolesRequest) ProtoMessage()    {}
func (*GetRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{10}
}
func (m *GetRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesRequest.Unmarshal(m, b)
}
func (m *GetRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesRequest.Marshal(b, m, deterministic)
}
func (dst *GetRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesRequest.Merge(dst, src)
}
func (m *GetRolesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRolesRequest.Size(m)
}
func (m *GetRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesRequest proto.InternalMessageInfo

type GetRolesResponse struct {
	Roles                []*Role  `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty" bson:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesResponse) Reset()         { *m = GetRolesResponse{} }
func (m *GetRolesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRolesResponse) ProtoMessage()    {}
func (*GetRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{11}
}
func (m *GetRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesResponse.Unmarshal(m, b)
}
func (m *GetRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesResponse.Marshal(b, m, deterministic)
}
func (dst *GetRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesResponse.Merge(dst, src)
}
func (m *GetRolesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRolesResponse.Size(m)
}
func (m *GetRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesResponse proto.InternalMessageInfo

func (m *GetRolesResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type UpdateRoleRequest struct {
	RoleName             string   `protobuf:"bytes,1,opt,name=RoleName,proto3" json:"RoleName,omitempty" bson:"RoleName,omitempty"`
	Role                 *Role    `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty" bson:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleRequest) Reset()         { *m = UpdateRoleRequest{} }
func (m *UpdateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleRequest) ProtoMessage()    {}
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{12}
}
func (m *UpdateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleRequest.Unmarshal(m, b)
}
func (m *UpdateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleRequest.Merge(dst, src)
}
func (m *UpdateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleRequest.Size(m)
}
func (m *UpdateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleRequest proto.InternalMessageInfo

func (m *UpdateRoleRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *UpdateRoleRequest) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type UpdateRoleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleResponse) Reset()         { *m = UpdateRoleResponse{} }
func (m *UpdateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleResponse) ProtoMessage()    {}
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{13}
}
func (m *UpdateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleResponse.Unmarshal(m, b)
}
func (m *UpdateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleResponse.Merge(dst, src)
}
func (m *UpdateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleResponse.Size(m)
}
func (m *UpdateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleResponse proto.InternalMessageInfo

type UpdatePrincipalRequest struct {
	Principal            *Principal `protobuf:"bytes,1,opt,name=Principal,proto3" json:"Principal,omitempty" bson:"Principal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdatePrincipalRequest) Reset()         { *m = UpdatePrincipalRequest{} }
func (m *UpdatePrincipalRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePrincipalRequest) ProtoMessage()    {}
func (*UpdatePrincipalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{14}
}
func (m *UpdatePrincipalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePrincipalRequest.Unmarshal(m, b)
}
func (m *UpdatePrincipalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePrincipalRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePrincipalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePrincipalRequest.Merge(dst, src)
}
func (m *UpdatePrincipalRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePrincipalRequest.Size(m)
}
func (m *UpdatePrincipalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePrincipalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePrincipalRequest proto.InternalMessageInfo

func (m *UpdatePrincipalRequest) GetPrincipal() *Principal {
	if m != nil {
		return m.Principal
	}
	return nil
}

type UpdatePrincipalResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePrincipalResponse) Reset()         { *m = UpdatePrincipalResponse{} }
func (m *UpdatePrincipalResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePrincipalResponse) ProtoMessage()    {}
func (*UpdatePrincipalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authn_1b8f26c962ace9cd, []int{15}
}
func (m *UpdatePrincipalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePrincipalResponse.Unmarshal(m, b)
}
func (m *UpdatePrincipalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePrincipalResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatePrincipalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePrincipalResponse.Merge(dst, src)
}
func (m *UpdatePrincipalResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePrincipalResponse.Size(m)
}
func (m *UpdatePrincipalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePrincipalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePrincipalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Principal)(nil), "grpc.authn.v1.Principal")
	proto.RegisterType((*Role)(nil), "grpc.authn.v1.Role")
	proto.RegisterType((*NotifyMFARequest)(nil), "grpc.authn.v1.NotifyMFARequest")
	proto.RegisterType((*NotifyMFAResponse)(nil), "grpc.authn.v1.NotifyMFAResponse")
	proto.RegisterType((*AuthenticateRequest)(nil), "grpc.authn.v1.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "grpc.authn.v1.AuthenticateResponse")
	proto.RegisterType((*GetPrincipalPermissionsRequest)(nil), "grpc.authn.v1.GetPrincipalPermissionsRequest")
	proto.RegisterType((*GetPrincipalPermissionsResponse)(nil), "grpc.authn.v1.GetPrincipalPermissionsResponse")
	proto.RegisterType((*AddDomainRealmRequest)(nil), "grpc.authn.v1.AddDomainRealmRequest")
	proto.RegisterType((*AddDomainRealmResponse)(nil), "grpc.authn.v1.AddDomainRealmResponse")
	proto.RegisterType((*GetRolesRequest)(nil), "grpc.authn.v1.GetRolesRequest")
	proto.RegisterType((*GetRolesResponse)(nil), "grpc.authn.v1.GetRolesResponse")
	proto.RegisterType((*UpdateRoleRequest)(nil), "grpc.authn.v1.UpdateRoleRequest")
	proto.RegisterType((*UpdateRoleResponse)(nil), "grpc.authn.v1.UpdateRoleResponse")
	proto.RegisterType((*UpdatePrincipalRequest)(nil), "grpc.authn.v1.UpdatePrincipalRequest")
	proto.RegisterType((*UpdatePrincipalResponse)(nil), "grpc.authn.v1.UpdatePrincipalResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UnifiedUserManagementClient is the client API for UnifiedUserManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnifiedUserManagementClient interface {
	// NotifyMFA will post a mfa code to client
	NotifyMFA(ctx context.Context, in *NotifyMFARequest, opts ...grpc.CallOption) (*NotifyMFAResponse, error)
	// Authenticate authenticate the principal in specific domain realm
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// GetPrincipalPermissions return principal's role's permissions used by
	// dashboard
	GetPrincipalPermissions(ctx context.Context, in *GetPrincipalPermissionsRequest, opts ...grpc.CallOption) (*GetPrincipalPermissionsResponse, error)
	// AddDomainRealm adds specific realm
	AddDomainRealm(ctx context.Context, in *AddDomainRealmRequest, opts ...grpc.CallOption) (*AddDomainRealmResponse, error)
	// GetRoles return all roles's permissions
	GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesResponse, error)
	// UpdateRole update principal's role
	UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error)
	// UpdatePrincipal update principal detail
	UpdatePrincipal(ctx context.Context, in *UpdatePrincipalRequest, opts ...grpc.CallOption) (*UpdatePrincipalResponse, error)
}

type unifiedUserManagementClient struct {
	cc *grpc.ClientConn
}

func NewUnifiedUserManagementClient(cc *grpc.ClientConn) UnifiedUserManagementClient {
	return &unifiedUserManagementClient{cc}
}

func (c *unifiedUserManagementClient) NotifyMFA(ctx context.Context, in *NotifyMFARequest, opts ...grpc.CallOption) (*NotifyMFAResponse, error) {
	out := new(NotifyMFAResponse)
	err := c.cc.Invoke(ctx, "/grpc.authn.v1.UnifiedUserManagement/NotifyMFA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedUserManagementClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/grpc.authn.v1.UnifiedUserManagement/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedUserManagementClient) GetPrincipalPermissions(ctx context.Context, in *GetPrincipalPermissionsRequest, opts ...grpc.CallOption) (*GetPrincipalPermissionsResponse, error) {
	out := new(GetPrincipalPermissionsResponse)
	err := c.cc.Invoke(ctx, "/grpc.authn.v1.UnifiedUserManagement/GetPrincipalPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedUserManagementClient) AddDomainRealm(ctx context.Context, in *AddDomainRealmRequest, opts ...grpc.CallOption) (*AddDomainRealmResponse, error) {
	out := new(AddDomainRealmResponse)
	err := c.cc.Invoke(ctx, "/grpc.authn.v1.UnifiedUserManagement/AddDomainRealm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedUserManagementClient) GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesResponse, error) {
	out := new(GetRolesResponse)
	err := c.cc.Invoke(ctx, "/grpc.authn.v1.UnifiedUserManagement/GetRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedUserManagementClient) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error) {
	out := new(UpdateRoleResponse)
	err := c.cc.Invoke(ctx, "/grpc.authn.v1.UnifiedUserManagement/UpdateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedUserManagementClient) UpdatePrincipal(ctx context.Context, in *UpdatePrincipalRequest, opts ...grpc.CallOption) (*UpdatePrincipalResponse, error) {
	out := new(UpdatePrincipalResponse)
	err := c.cc.Invoke(ctx, "/grpc.authn.v1.UnifiedUserManagement/UpdatePrincipal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnifiedUserManagementServer is the server API for UnifiedUserManagement service.
type UnifiedUserManagementServer interface {
	// NotifyMFA will post a mfa code to client
	NotifyMFA(context.Context, *NotifyMFARequest) (*NotifyMFAResponse, error)
	// Authenticate authenticate the principal in specific domain realm
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	// GetPrincipalPermissions return principal's role's permissions used by
	// dashboard
	GetPrincipalPermissions(context.Context, *GetPrincipalPermissionsRequest) (*GetPrincipalPermissionsResponse, error)
	// AddDomainRealm adds specific realm
	AddDomainRealm(context.Context, *AddDomainRealmRequest) (*AddDomainRealmResponse, error)
	// GetRoles return all roles's permissions
	GetRoles(context.Context, *GetRolesRequest) (*GetRolesResponse, error)
	// UpdateRole update principal's role
	UpdateRole(context.Context, *UpdateRoleRequest) (*UpdateRoleResponse, error)
	// UpdatePrincipal update principal detail
	UpdatePrincipal(context.Context, *UpdatePrincipalRequest) (*UpdatePrincipalResponse, error)
}

func RegisterUnifiedUserManagementServer(s *grpc.Server, srv UnifiedUserManagementServer) {
	s.RegisterService(&_UnifiedUserManagement_serviceDesc, srv)
}

func _UnifiedUserManagement_NotifyMFA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyMFARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).NotifyMFA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.authn.v1.UnifiedUserManagement/NotifyMFA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).NotifyMFA(ctx, req.(*NotifyMFARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedUserManagement_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.authn.v1.UnifiedUserManagement/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedUserManagement_GetPrincipalPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrincipalPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).GetPrincipalPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.authn.v1.UnifiedUserManagement/GetPrincipalPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).GetPrincipalPermissions(ctx, req.(*GetPrincipalPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedUserManagement_AddDomainRealm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDomainRealmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).AddDomainRealm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.authn.v1.UnifiedUserManagement/AddDomainRealm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).AddDomainRealm(ctx, req.(*AddDomainRealmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedUserManagement_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.authn.v1.UnifiedUserManagement/GetRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).GetRoles(ctx, req.(*GetRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedUserManagement_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.authn.v1.UnifiedUserManagement/UpdateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).UpdateRole(ctx, req.(*UpdateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedUserManagement_UpdatePrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).UpdatePrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.authn.v1.UnifiedUserManagement/UpdatePrincipal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).UpdatePrincipal(ctx, req.(*UpdatePrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnifiedUserManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.authn.v1.UnifiedUserManagement",
	HandlerType: (*UnifiedUserManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyMFA",
			Handler:    _UnifiedUserManagement_NotifyMFA_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _UnifiedUserManagement_Authenticate_Handler,
		},
		{
			MethodName: "GetPrincipalPermissions",
			Handler:    _UnifiedUserManagement_GetPrincipalPermissions_Handler,
		},
		{
			MethodName: "AddDomainRealm",
			Handler:    _UnifiedUserManagement_AddDomainRealm_Handler,
		},
		{
			MethodName: "GetRoles",
			Handler:    _UnifiedUserManagement_GetRoles_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _UnifiedUserManagement_UpdateRole_Handler,
		},
		{
			MethodName: "UpdatePrincipal",
			Handler:    _UnifiedUserManagement_UpdatePrincipal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authn.proto",
}

func init() { proto.RegisterFile("authn.proto", fileDescriptor_authn_1b8f26c962ace9cd) }

var fileDescriptor_authn_1b8f26c962ace9cd = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xa5, 0x69, 0x87, 0xd6, 0x5b, 0xd8, 0x5a, 0xb7, 0x5b, 0x43, 0x1e, 0xd6, 0x12, 0x18, 0x94,
	0x07, 0x2a, 0x51, 0x24, 0x9e, 0xe0, 0xa1, 0xa8, 0xda, 0x34, 0x44, 0xa7, 0x28, 0x50, 0x09, 0x9e,
	0xa6, 0xac, 0xf1, 0x36, 0x8b, 0xc6, 0x0e, 0x71, 0x06, 0x82, 0x7f, 0xc4, 0xbf, 0x44, 0xce, 0x87,
	0xe3, 0xba, 0x4d, 0x3b, 0x69, 0x6f, 0xbe, 0x1f, 0x3e, 0xf7, 0xf8, 0xdc, 0x13, 0x05, 0x1a, 0xfc,
	0x86, 0x44, 0x6c, 0x18, 0x46, 0x2c, 0x66, 0xe8, 0xf1, 0x75, 0x14, 0xce, 0x87, 0x69, 0xe6, 0xd7,
	0x1b, 0x9b, 0x40, 0xdd, 0x89, 0x08, 0x9d, 0x93, 0xd0, 0x5b, 0xa0, 0x3d, 0x30, 0xce, 0x26, 0x66,
	0xa5, 0x5f, 0x19, 0xd4, 0x5d, 0xe3, 0x6c, 0x82, 0x2c, 0xd8, 0x9d, 0x71, 0x1c, 0x51, 0x2f, 0xc0,
	0xa6, 0x91, 0x64, 0x65, 0x2c, 0x6a, 0x8e, 0xc7, 0xf9, 0x6f, 0x16, 0xf9, 0x66, 0x35, 0xad, 0xe5,
	0x31, 0xea, 0xc0, 0x8e, 0xcb, 0x16, 0x98, 0x9b, 0xb5, 0x7e, 0x75, 0x50, 0x77, 0xd3, 0xc0, 0x7e,
	0x0f, 0x35, 0x71, 0x40, 0x08, 0x6a, 0xe7, 0x02, 0x31, 0x9d, 0x93, 0x9c, 0x51, 0x1f, 0x1a, 0x0e,
	0x8e, 0x02, 0xc2, 0x39, 0x61, 0x94, 0x9b, 0x46, 0x72, 0x4f, 0x4d, 0xd9, 0x9f, 0xa0, 0x79, 0xce,
	0x62, 0x72, 0xf5, 0x67, 0x7a, 0x32, 0x76, 0xf1, 0xcf, 0x5b, 0xcc, 0x63, 0xf4, 0x4e, 0x21, 0x9f,
	0xc0, 0x35, 0x46, 0xe6, 0x70, 0xe9, 0x7d, 0x43, 0x59, 0x77, 0x8b, 0x56, 0xbb, 0x0d, 0x2d, 0x05,
	0x8b, 0x87, 0x8c, 0x72, 0x6c, 0x5f, 0x40, 0x7b, 0x7c, 0x1b, 0xdf, 0x60, 0x1a, 0x93, 0xb9, 0x17,
	0xe3, 0x7c, 0x86, 0xaa, 0x41, 0x65, 0x83, 0x06, 0x86, 0xa6, 0x41, 0x13, 0xaa, 0xd3, 0x93, 0x71,
	0x26, 0x8d, 0x38, 0xda, 0x1f, 0xa1, 0xb3, 0x3c, 0x20, 0x1d, 0x2c, 0xd4, 0xfa, 0xca, 0x7e, 0x60,
	0x9a, 0xc1, 0xa7, 0x41, 0xa1, 0xa1, 0xa1, 0x6a, 0xf8, 0x0d, 0x8e, 0x4e, 0x71, 0x2c, 0x5f, 0xa2,
	0x08, 0x74, 0x5f, 0x4d, 0x3e, 0x43, 0xaf, 0x14, 0x39, 0x23, 0xfa, 0x2a, 0xa7, 0x54, 0xe9, 0x57,
	0x07, 0x8d, 0x51, 0x5b, 0x83, 0x15, 0xb5, 0x9c, 0x67, 0x17, 0x0e, 0xc6, 0xbe, 0x3f, 0x61, 0x81,
	0x47, 0xa8, 0x8b, 0xbd, 0x45, 0x90, 0xd1, 0xb3, 0x4d, 0x38, 0xd4, 0x0b, 0x99, 0xfe, 0x2d, 0xd8,
	0x3f, 0xc5, 0x71, 0x72, 0x3d, 0x6f, 0xfe, 0x00, 0xcd, 0x22, 0x55, 0x90, 0x88, 0xb6, 0x92, 0x88,
	0x32, 0xb1, 0x5a, 0xb3, 0xd0, 0x17, 0x52, 0x8b, 0x64, 0xb1, 0x4f, 0x11, 0x2a, 0x0e, 0x94, 0x31,
	0x7a, 0x99, 0x3a, 0x34, 0xd9, 0x65, 0x09, 0x74, 0xd2, 0x60, 0x77, 0x00, 0xa9, 0xc8, 0xd9, 0x0b,
	0x1c, 0x38, 0x4c, 0xb3, 0x85, 0xc0, 0xf7, 0x5c, 0xca, 0x13, 0xe8, 0xae, 0x20, 0xa6, 0xc3, 0x46,
	0xff, 0x76, 0xe0, 0x60, 0x46, 0xc9, 0x15, 0xc1, 0xbe, 0xf0, 0xe3, 0xd4, 0xa3, 0xde, 0x35, 0x0e,
	0x30, 0x8d, 0x91, 0x03, 0x75, 0xe9, 0x6e, 0xd4, 0xd3, 0xc6, 0xe8, 0xdf, 0x90, 0xd5, 0x2f, 0x6f,
	0xc8, 0x9e, 0xf5, 0x00, 0x7d, 0x87, 0x47, 0xaa, 0x73, 0x91, 0xad, 0xdd, 0x59, 0xf3, 0xdd, 0x58,
	0xcf, 0x36, 0xf6, 0x48, 0xe8, 0xbf, 0xd0, 0x2d, 0xb1, 0x1d, 0x7a, 0xad, 0x21, 0x6c, 0x36, 0xbe,
	0x35, 0xbc, 0x6b, 0xbb, 0x9c, 0x7d, 0x01, 0x7b, 0xcb, 0x5e, 0x44, 0xcf, 0x75, 0xd2, 0xeb, 0x3c,
	0x6c, 0x1d, 0x6f, 0xe9, 0x92, 0x03, 0xa6, 0xb0, 0x9b, 0xfb, 0x17, 0x1d, 0xad, 0xd2, 0x53, 0xbd,
	0x6e, 0xf5, 0x4a, 0xeb, 0x12, 0xee, 0x0b, 0x40, 0xe1, 0x3a, 0xa4, 0x2f, 0x6e, 0xc5, 0xea, 0xd6,
	0xd3, 0x0d, 0x1d, 0x12, 0xf4, 0x12, 0xf6, 0x35, 0x8b, 0xa1, 0xe3, 0xb5, 0xf7, 0x74, 0x53, 0x5b,
	0x2f, 0xb6, 0xb5, 0xe5, 0x33, 0x2e, 0x1f, 0x26, 0xbf, 0x9e, 0xb7, 0xff, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xec, 0xe4, 0x70, 0xc4, 0x89, 0x06, 0x00, 0x00,
}
