FROM pandas/pandas-base 

LABEL vendor=pandas
LABEL product=pandas

# ADD certs/* /etc/ssl/pandas
ADD pandas/cmd/swagger/bin/* /
ADD pandas/cmd/swagger/downstreams.json /
RUN chmod 755 /main
RUN chmod 755 /dockerize

USER root

CMD ["/main"]
