// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shiro.proto

package grpc_shiro_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MFArgs struct {
	SignName             string   `protobuf:"bytes,1,opt,name=SignName,proto3" json:"SignName,omitempty" bson:"SignName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MFArgs) Reset()         { *m = MFArgs{} }
func (m *MFArgs) String() string { return proto.CompactTextString(m) }
func (*MFArgs) ProtoMessage()    {}
func (*MFArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_shiro_e804704c12cb0cd2, []int{0}
}
func (m *MFArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MFArgs.Unmarshal(m, b)
}
func (m *MFArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MFArgs.Marshal(b, m, deterministic)
}
func (dst *MFArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MFArgs.Merge(dst, src)
}
func (m *MFArgs) XXX_Size() int {
	return xxx_messageInfo_MFArgs.Size(m)
}
func (m *MFArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_MFArgs.DiscardUnknown(m)
}

var xxx_messageInfo_MFArgs proto.InternalMessageInfo

func (m *MFArgs) GetSignName() string {
	if m != nil {
		return m.SignName
	}
	return ""
}

type AuthenticateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty" bson:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty" bson:"Password,omitempty"`
	Mfa                  *MFArgs  `protobuf:"bytes,3,opt,name=mfa,proto3" json:"mfa,omitempty" bson:"mfa,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shiro_e804704c12cb0cd2, []int{1}
}
func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(dst, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthenticateRequest) GetMfa() *MFArgs {
	if m != nil {
		return m.Mfa
	}
	return nil
}

type AuthenticateResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty" bson:"Token,omitempty"`
	Roles                []string `protobuf:"bytes,2,rep,name=Roles,proto3" json:"Roles,omitempty" bson:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shiro_e804704c12cb0cd2, []int{2}
}
func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(dst, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthenticateResponse) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type AddDomainRealmRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDomainRealmRequest) Reset()         { *m = AddDomainRealmRequest{} }
func (m *AddDomainRealmRequest) String() string { return proto.CompactTextString(m) }
func (*AddDomainRealmRequest) ProtoMessage()    {}
func (*AddDomainRealmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shiro_e804704c12cb0cd2, []int{3}
}
func (m *AddDomainRealmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDomainRealmRequest.Unmarshal(m, b)
}
func (m *AddDomainRealmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDomainRealmRequest.Marshal(b, m, deterministic)
}
func (dst *AddDomainRealmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDomainRealmRequest.Merge(dst, src)
}
func (m *AddDomainRealmRequest) XXX_Size() int {
	return xxx_messageInfo_AddDomainRealmRequest.Size(m)
}
func (m *AddDomainRealmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDomainRealmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDomainRealmRequest proto.InternalMessageInfo

type AddDomainRealmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDomainRealmResponse) Reset()         { *m = AddDomainRealmResponse{} }
func (m *AddDomainRealmResponse) String() string { return proto.CompactTextString(m) }
func (*AddDomainRealmResponse) ProtoMessage()    {}
func (*AddDomainRealmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shiro_e804704c12cb0cd2, []int{4}
}
func (m *AddDomainRealmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDomainRealmResponse.Unmarshal(m, b)
}
func (m *AddDomainRealmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDomainRealmResponse.Marshal(b, m, deterministic)
}
func (dst *AddDomainRealmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDomainRealmResponse.Merge(dst, src)
}
func (m *AddDomainRealmResponse) XXX_Size() int {
	return xxx_messageInfo_AddDomainRealmResponse.Size(m)
}
func (m *AddDomainRealmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDomainRealmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDomainRealmResponse proto.InternalMessageInfo

type GetRolePermissionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolePermissionsRequest) Reset()         { *m = GetRolePermissionsRequest{} }
func (m *GetRolePermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRolePermissionsRequest) ProtoMessage()    {}
func (*GetRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shiro_e804704c12cb0cd2, []int{5}
}
func (m *GetRolePermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolePermissionsRequest.Unmarshal(m, b)
}
func (m *GetRolePermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolePermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *GetRolePermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolePermissionsRequest.Merge(dst, src)
}
func (m *GetRolePermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRolePermissionsRequest.Size(m)
}
func (m *GetRolePermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolePermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolePermissionsRequest proto.InternalMessageInfo

type GetRolePermissionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolePermissionsResponse) Reset()         { *m = GetRolePermissionsResponse{} }
func (m *GetRolePermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRolePermissionsResponse) ProtoMessage()    {}
func (*GetRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shiro_e804704c12cb0cd2, []int{6}
}
func (m *GetRolePermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolePermissionsResponse.Unmarshal(m, b)
}
func (m *GetRolePermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolePermissionsResponse.Marshal(b, m, deterministic)
}
func (dst *GetRolePermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolePermissionsResponse.Merge(dst, src)
}
func (m *GetRolePermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRolePermissionsResponse.Size(m)
}
func (m *GetRolePermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolePermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolePermissionsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MFArgs)(nil), "grpc.shiro.v1.MFArgs")
	proto.RegisterType((*AuthenticateRequest)(nil), "grpc.shiro.v1.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "grpc.shiro.v1.AuthenticateResponse")
	proto.RegisterType((*AddDomainRealmRequest)(nil), "grpc.shiro.v1.AddDomainRealmRequest")
	proto.RegisterType((*AddDomainRealmResponse)(nil), "grpc.shiro.v1.AddDomainRealmResponse")
	proto.RegisterType((*GetRolePermissionsRequest)(nil), "grpc.shiro.v1.GetRolePermissionsRequest")
	proto.RegisterType((*GetRolePermissionsResponse)(nil), "grpc.shiro.v1.GetRolePermissionsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UnifiedUserManagementClient is the client API for UnifiedUserManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnifiedUserManagementClient interface {
	// Authenticate authenticate the principal in specific domain realm
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// AddDomainRealm adds specific realm
	AddDomainRealm(ctx context.Context, in *AddDomainRealmRequest, opts ...grpc.CallOption) (*AddDomainRealmResponse, error)
	// GetRolePermissions return role's dynamica route path
	GetRolePermissions(ctx context.Context, in *GetRolePermissionsRequest, opts ...grpc.CallOption) (*GetRolePermissionsResponse, error)
}

type unifiedUserManagementClient struct {
	cc *grpc.ClientConn
}

func NewUnifiedUserManagementClient(cc *grpc.ClientConn) UnifiedUserManagementClient {
	return &unifiedUserManagementClient{cc}
}

func (c *unifiedUserManagementClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/grpc.shiro.v1.UnifiedUserManagement/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedUserManagementClient) AddDomainRealm(ctx context.Context, in *AddDomainRealmRequest, opts ...grpc.CallOption) (*AddDomainRealmResponse, error) {
	out := new(AddDomainRealmResponse)
	err := c.cc.Invoke(ctx, "/grpc.shiro.v1.UnifiedUserManagement/AddDomainRealm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedUserManagementClient) GetRolePermissions(ctx context.Context, in *GetRolePermissionsRequest, opts ...grpc.CallOption) (*GetRolePermissionsResponse, error) {
	out := new(GetRolePermissionsResponse)
	err := c.cc.Invoke(ctx, "/grpc.shiro.v1.UnifiedUserManagement/GetRolePermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnifiedUserManagementServer is the server API for UnifiedUserManagement service.
type UnifiedUserManagementServer interface {
	// Authenticate authenticate the principal in specific domain realm
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	// AddDomainRealm adds specific realm
	AddDomainRealm(context.Context, *AddDomainRealmRequest) (*AddDomainRealmResponse, error)
	// GetRolePermissions return role's dynamica route path
	GetRolePermissions(context.Context, *GetRolePermissionsRequest) (*GetRolePermissionsResponse, error)
}

func RegisterUnifiedUserManagementServer(s *grpc.Server, srv UnifiedUserManagementServer) {
	s.RegisterService(&_UnifiedUserManagement_serviceDesc, srv)
}

func _UnifiedUserManagement_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.shiro.v1.UnifiedUserManagement/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedUserManagement_AddDomainRealm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDomainRealmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).AddDomainRealm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.shiro.v1.UnifiedUserManagement/AddDomainRealm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).AddDomainRealm(ctx, req.(*AddDomainRealmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedUserManagement_GetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedUserManagementServer).GetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.shiro.v1.UnifiedUserManagement/GetRolePermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedUserManagementServer).GetRolePermissions(ctx, req.(*GetRolePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnifiedUserManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.shiro.v1.UnifiedUserManagement",
	HandlerType: (*UnifiedUserManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _UnifiedUserManagement_Authenticate_Handler,
		},
		{
			MethodName: "AddDomainRealm",
			Handler:    _UnifiedUserManagement_AddDomainRealm_Handler,
		},
		{
			MethodName: "GetRolePermissions",
			Handler:    _UnifiedUserManagement_GetRolePermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shiro.proto",
}

func init() { proto.RegisterFile("shiro.proto", fileDescriptor_shiro_e804704c12cb0cd2) }

var fileDescriptor_shiro_e804704c12cb0cd2 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4e, 0x02, 0x31,
	0x10, 0x16, 0x88, 0x44, 0x07, 0xf5, 0x50, 0x41, 0xd7, 0xd5, 0x03, 0xa9, 0x18, 0xf1, 0xb2, 0x89,
	0xf8, 0x04, 0x18, 0xa3, 0x27, 0x0c, 0x59, 0xe5, 0xe0, 0xc9, 0x54, 0x76, 0x58, 0x1a, 0xd8, 0x16,
	0x3b, 0x05, 0x5f, 0xcf, 0x47, 0x33, 0x65, 0x59, 0x02, 0x2b, 0xfe, 0x1c, 0xbf, 0x99, 0xf9, 0xfa,
	0xfd, 0xa4, 0x50, 0xa1, 0xa1, 0x34, 0x3a, 0x98, 0x18, 0x6d, 0x35, 0xdb, 0x8f, 0xcd, 0xa4, 0x1f,
	0xa4, 0x93, 0xd9, 0x35, 0x6f, 0x40, 0xb9, 0x73, 0xdf, 0x36, 0x31, 0x31, 0x1f, 0x76, 0x9e, 0x64,
	0xac, 0x1e, 0x45, 0x82, 0x5e, 0xa1, 0x5e, 0x68, 0xee, 0x86, 0x4b, 0xcc, 0x67, 0x70, 0xd8, 0x9e,
	0xda, 0x21, 0x2a, 0x2b, 0xfb, 0xc2, 0x62, 0x88, 0xef, 0x53, 0x24, 0xeb, 0x28, 0x3d, 0x42, 0xa3,
	0x56, 0x28, 0x19, 0x76, 0xbb, 0xae, 0x20, 0xfa, 0xd0, 0x26, 0xf2, 0x8a, 0xe9, 0x2e, 0xc3, 0xec,
	0x12, 0x4a, 0xc9, 0x40, 0x78, 0xa5, 0x7a, 0xa1, 0x59, 0x69, 0xd5, 0x82, 0x35, 0x47, 0x41, 0x6a,
	0x27, 0x74, 0x17, 0xfc, 0x16, 0xaa, 0xeb, 0xba, 0x34, 0xd1, 0x8a, 0x90, 0x55, 0x61, 0xfb, 0x59,
	0x8f, 0x50, 0x2d, 0x54, 0x53, 0xe0, 0xa6, 0xa1, 0x1e, 0x23, 0x79, 0xc5, 0x7a, 0xc9, 0x4d, 0xe7,
	0x80, 0x1f, 0x43, 0xad, 0x1d, 0x45, 0x77, 0x3a, 0x11, 0x52, 0x85, 0x28, 0xc6, 0xc9, 0xc2, 0x3d,
	0xf7, 0xe0, 0x28, 0xbf, 0x48, 0x9f, 0xe7, 0xa7, 0x70, 0xf2, 0x80, 0xd6, 0xd1, 0xbb, 0x68, 0x12,
	0x49, 0x24, 0xb5, 0xa2, 0x8c, 0x76, 0x06, 0xfe, 0xa6, 0x65, 0x4a, 0x6d, 0x7d, 0x16, 0xa1, 0xd6,
	0x53, 0x72, 0x20, 0x31, 0x72, 0x55, 0x74, 0x84, 0x12, 0x31, 0x26, 0xa8, 0x2c, 0x7b, 0x81, 0xbd,
	0xd5, 0x2c, 0x8c, 0xe7, 0x72, 0x6f, 0x28, 0xd8, 0x3f, 0xff, 0xf5, 0x66, 0xe1, 0x76, 0x8b, 0xbd,
	0xc2, 0xc1, 0x7a, 0x12, 0xd6, 0xc8, 0x13, 0x37, 0x35, 0xe0, 0x5f, 0xfc, 0x71, 0xb5, 0x14, 0x18,
	0x01, 0xfb, 0x9e, 0x99, 0x35, 0x73, 0xf4, 0x1f, 0x3b, 0xf3, 0xaf, 0xfe, 0x71, 0x99, 0x89, 0xbd,
	0x95, 0xe7, 0x1f, 0xf5, 0xe6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x62, 0x36, 0xdb, 0xc7, 0xb7, 0x02,
	0x00, 0x00,
}
