version: "2"

volumes:
  pandas-authn-db-volume:
  pandas-users-db-volume:
  pandas-things-db-volume:
  pandas-things-redis-volume:
  pandas-es-redis-volume:
  pandas-mqtt-broker-volume:
  pandas-lbs-db-volume:
  pandas-bootstrap-db-volume:
  pandas-twins-db-volume:
  pandas-twins-db-configdb-volume:
  pandas-vms-db-volume:
  pandas-vms-redis-volume:
  pandas-pms-db-volume:
  pandas-pms-redis-volume:
  pandas-realms-db-volume:
  pandas-kuiper-db-volume:

services:
  nats:
    image: nats:1.3.0
    container_name: pandas-nats
    command: "-c /etc/nats/nats.conf"
    restart: on-failure
    volumes:
      - ./nats/:/etc/nats
  jaeger:
    image: jaegertracing/all-in-one:1.13
    container_name: pandas-jaeger
    ports:
      - ${PD_JAEGER_PORT}:${PD_JAEGER_PORT}/udp
      - ${PD_JAEGER_FRONTEND}:${PD_JAEGER_FRONTEND}
      - ${PD_JAEGER_COLLECTOR}:${PD_JAEGER_COLLECTOR}
      - ${PD_JAEGER_CONFIGS}:${PD_JAEGER_CONFIGS}

  authn-db:
    image: postgres:10.8-alpine
    container_name: pandas-authn-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PD_AUTHN_DB_USER}
      POSTGRES_PASSWORD: ${PD_AUTHN_DB_PASS}
      POSTGRES_DB: ${PD_AUTHN_DB}
    volumes:
      - pandas-authn-db-volume:/var/lib/postgresql/data

  authn:
    image: pandas/pandas-authn:latest
    container_name: pandas-authn
    depends_on:
      - authn-db
    expose:
      - ${PD_AUTHN_GRPC_PORT}
    ports:
      - ${PD_AUTHN_HTTP_PORT}:${PD_AUTHN_HTTP_PORT}
      - ${PD_AUTHN_GRPC_PORT}:${PD_AUTHN_GRPC_PORT}
    restart: always
    environment:
      PD_AUTHN_HTTP_PORT: ${PD_AUTHN_HTTP_PORT}
      PANDAS_DNS_SERVER: "docker-compose"
      PD_AUTHN_LOG_LEVEL: ${PD_AUTHN_LOG_LEVEL}
      PD_AUTHN_DB_HOST: authn-db
      PD_AUTHN_DB_PORT: ${PD_AUTHN_DB_PORT}
      PD_AUTHN_DB_USER: ${PD_AUTHN_DB_USER}
      PD_AUTHN_DB_PASS: ${PD_AUTHN_DB_PASS}
      PD_AUTHN_DB: ${PD_AUTHN_DB}
      PD_AUTHN_HTTP_PORT: ${PD_AUTHN_HTTP_PORT}
      PD_AUTHN_GRPC_PORT: ${PD_AUTHN_GRPC_PORT}
      PD_AUTHN_SECRET: ${PD_AUTHN_SECRET}
      PD_JAEGER_URL: ${PD_JAEGER_URL}

  things-db:
    image: postgres:10.8-alpine
    container_name: pandas-things-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PD_THINGS_DB_USER}
      POSTGRES_PASSWORD: ${PD_THINGS_DB_PASS}
      POSTGRES_DB: ${PD_THINGS_DB}
    volumes:
      - pandas-things-db-volume:/var/lib/postgresql/data

  things-redis:
    image: redis:5.0-alpine
    container_name: pandas-things-redis
    restart: on-failure
    volumes:
      - pandas-things-redis-volume:/data

  things:
    image: pandas/pandas-things:latest
    container_name: pandas-things
    depends_on:
      - things-db
      - authn
    restart: on-failure
    environment:
      PD_THINGS_LOG_LEVEL: ${PD_THINGS_LOG_LEVEL}
      PD_THINGS_DB_HOST: things-db
      PD_THINGS_DB_PORT: ${PD_THINGS_DB_PORT}
      PD_THINGS_DB_USER: ${PD_THINGS_DB_USER}
      PD_THINGS_DB_PASS: ${PD_THINGS_DB_PASS}
      PD_THINGS_DB: ${PD_THINGS_DB}
      PD_THINGS_CACHE_URL: things-redis:${PD_REDIS_TCP_PORT}
      PD_THINGS_ES_URL: es-redis:${PD_REDIS_TCP_PORT}
      PD_THINGS_HTTP_PORT: ${PD_THINGS_HTTP_PORT}
      PD_THINGS_AUTH_HTTP_PORT: ${PD_THINGS_AUTH_HTTP_PORT}
      PD_THINGS_AUTH_GRPC_PORT: ${PD_THINGS_AUTH_GRPC_PORT}
      PD_AUTH_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_THINGS_SECRET: ${PD_THINGS_SECRET}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
    ports:
      - ${PD_THINGS_HTTP_PORT}:${PD_THINGS_HTTP_PORT}
      - ${PD_THINGS_AUTH_HTTP_PORT}:${PD_THINGS_AUTH_HTTP_PORT}
      - ${PD_THINGS_AUTH_GRPC_PORT}:${PD_THINGS_AUTH_GRPC_PORT}

  users-db:
    image: postgres:10.8-alpine
    container_name: pandas-users-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PD_USERS_DB_USER}
      POSTGRES_PASSWORD: ${PD_USERS_DB_PASS}
      POSTGRES_DB: ${PD_USERS_DB}
    volumes:
      - pandas-users-db-volume:/var/lib/postgresql/data

  users:
    image: pandas/pandas-users:latest
    container_name: pandas-users
    volumes:
      - ./users/emailer/templates/${PD_EMAIL_TEMPLATE}:/${PD_EMAIL_TEMPLATE}
    depends_on:
      - users-db
      - authn
    restart: on-failure
    environment:
      PD_USERS_LOG_LEVEL: ${PD_USERS_LOG_LEVEL}
      PD_USERS_DB_HOST: users-db
      PD_USERS_DB_PORT: ${PD_USERS_DB_PORT}
      PD_USERS_DB_USER: ${PD_USERS_DB_USER}
      PD_USERS_DB_PASS: ${PD_USERS_DB_PASS}
      PD_USERS_DB: ${PD_USERS_DB}
      PD_USERS_HTTP_PORT: ${PD_USERS_HTTP_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
      PD_EMAIL_DRIVER: ${PD_EMAIL_DRIVER}
      PD_EMAIL_HOST: ${PD_EMAIL_HOST}
      PD_EMAIL_PORT: ${PD_EMAIL_PORT}
      PD_EMAIL_USERNAME: ${PD_EMAIL_USERNAME}
      PD_EMAIL_PASSWORD: ${PD_EMAIL_PASSWORD}
      PD_EMAIL_FROM_ADDRESS: ${PD_EMAIL_FROM_ADDRESS}
      PD_EMAIL_FROM_NAME: ${PD_EMAIL_FROM_NAME}
      PD_EMAIL_TEMPLATE: ${PD_EMAIL_TEMPLATE}
      PD_TOKEN_RESET_ENDPOINT: ${PD_TOKEN_RESET_ENDPOINT}
      PD_AUTHN_URL: authn:${PD_AUTHN_GRPC_PORT}
    ports:
      - ${PD_USERS_HTTP_PORT}:${PD_USERS_HTTP_PORT}

  vernemq:
    image: mainflux/vernemq:1.10.1-alpine
    container_name: pandas-vernemq
    restart: on-failure
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: debug
    volumes:
      - pandas-mqtt-broker-volume:/var/lib/vernemq

  mqtt-adapter:
    image: pandas/pandas-mqtt:latest
    container_name: pandas-mqtt
    depends_on:
      - vernemq
      - things
      - nats
    restart: on-failure
    environment:
      PD_MQTT_ADAPTER_LOG_LEVEL: ${PD_MQTT_ADAPTER_LOG_LEVEL}
      PD_MQTT_ADAPTER_PORT: ${PD_MQTT_ADAPTER_PORT}
      PD_MQTT_ADAPTER_WS_PORT: ${PD_MQTT_ADAPTER_WS_PORT}
      PD_MQTT_ADAPTER_ES_URL: es-redis:${PD_REDIS_TCP_PORT}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_THINGS_URL: things:${PD_THINGS_AUTH_GRPC_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
      PD_MQTT_ADAPTER_MQTT_TARGET_HOST: vernemq
      PD_MQTT_ADAPTER_MQTT_TARGET_PORT: ${PD_MQTT_BROKER_PORT}
      PD_MQTT_ADAPTER_WS_TARGET_HOST: vernemq
      PD_MQTT_ADAPTER_WS_TARGET_PORT: ${PD_MQTT_BROKER_WS_PORT}

  ws-adapter:
    image: pandas/pandas-ws:latest
    container_name: pandas-ws
    depends_on:
      - things
      - nats
    restart: on-failure
    environment:
      PD_WS_ADAPTER_LOG_LEVEL: ${PD_WS_ADAPTER_LOG_LEVEL}
      PD_WS_ADAPTER_PORT: ${PD_WS_ADAPTER_PORT}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_THINGS_URL: things:${PD_THINGS_AUTH_GRPC_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
    ports:
      - ${PD_WS_ADAPTER_PORT}:${PD_WS_ADAPTER_PORT}

  http-adapter:
    image: pandas/pandas-http:latest
    container_name: pandas-http
    depends_on:
      - things
      - nats
    restart: on-failure
    environment:
      PD_HTTP_ADAPTER_LOG_LEVEL: debug
      PD_HTTP_ADAPTER_PORT: ${PD_HTTP_ADAPTER_PORT}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_THINGS_URL: things:${PD_THINGS_AUTH_GRPC_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
    ports:
      - ${PD_HTTP_ADAPTER_PORT}:${PD_HTTP_ADAPTER_PORT}

  es-redis:
    image: redis:5.0-alpine
    container_name: pandas-es-redis
    restart: on-failure
    volumes:
      - pandas-es-redis-volume:/data

  coap-adapter:
    image: pandas/pandas-coap:latest
    container_name: pandas-coap
    depends_on:
      - things
      - nats
    restart: on-failure
    environment:
      PD_COAP_ADAPTER_LOG_LEVEL: ${PD_COAP_ADAPTER_LOG_LEVEL}
      PD_COAP_ADAPTER_PORT: ${PD_COAP_ADAPTER_PORT}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_THINGS_URL: things:${PD_THINGS_AUTH_GRPC_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
    ports:
      - ${PD_COAP_ADAPTER_PORT}:${PD_COAP_ADAPTER_PORT}/udp
      - ${PD_COAP_ADAPTER_PORT}:${PD_COAP_ADAPTER_PORT}/tcp

  bootstrap-db:
    image: postgres:10.8-alpine
    container_name: pandas-bootstrap-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PD_BOOTSTRAP_DB_USER}
      POSTGRES_PASSWORD: ${PD_BOOTSTRAP_DB_PASS}
      POSTGRES_DB: ${PD_BOOTSTRAP_DB}
    volumes:
      - pandas-bootstrap-db-volume:/var/lib/postgresql/data

  bootstrap:
    image: pandas/pandas-bootstrap:latest
    container_name: pandas-bootstrap
    depends_on:
      - bootstrap-db
    restart: on-failure
    ports:
      - ${PD_BOOTSTRAP_PORT}:${PD_BOOTSTRAP_PORT}
    environment:
      PD_BOOTSTRAP_LOG_LEVEL: ${PD_BOOTSTRAP_LOG_LEVEL}
      PD_BOOTSTRAP_DB_HOST: bootstrap-db
      PD_BOOTSTRAP_DB_PORT: ${PD_BOOTSTRAP_DB_PORT}
      PD_BOOTSTRAP_DB_USER: ${PD_BOOTSTRAP_DB_USER}
      PD_BOOTSTRAP_DB_PASS: ${PD_BOOTSTRAP_DB_PASS}
      PD_BOOTSTRAP_DB: ${PD_BOOTSTRAP_DB}
      PD_BOOTSTRAP_DB_SSL_MODE: ${PD_BOOTSTRAP_DB_SSL_MODE}
      PD_BOOTSTRAP_PORT: ${PD_BOOTSTRAP_PORT}
      PD_SDK_BASE_URL: http://pandas-things:${PD_THINGS_HTTP_PORT}
      PD_AUTH_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_THINGS_ES_URL: es-redis:${PD_REDIS_TCP_PORT}
      PD_BOOTSTRAP_ES_URL: es-redis:${PD_REDIS_TCP_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}

  twins-db:
    image: mongo:bionic
    command: mongod --port ${PD_TWINS_DB_PORT}
    container_name: pandas-twins-db
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: ${PD_TWINS_DB_NAME}
    ports:
      - ${PD_TWINS_DB_PORT}:${PD_TWINS_DB_PORT}
    volumes:
      - pandas-twins-db-volume:/data/db      
      - pandas-twins-db-configdb-volume:/data/configdb

  twins:
    image: pandas/pandas-twins:latest
    container_name: pandas-twins
    restart: on-failure
    environment:
      PD_TWINS_LOG_LEVEL: ${PD_TWINS_LOG_LEVEL}
      PD_TWINS_HTTP_PORT: ${PD_TWINS_HTTP_PORT}
      PD_TWINS_DB_NAME: ${PD_TWINS_DB_NAME}
      PD_TWINS_DB_HOST: ${PD_TWINS_DB_HOST}
      PD_TWINS_DB_PORT: ${PD_TWINS_DB_PORT}
      PD_TWINS_THING_ID: ${PD_TWINS_THING_ID}
      PD_TWINS_THING_KEY: ${PD_TWINS_THING_KEY}
      PD_TWINS_CHANNEL_ID: ${PD_TWINS_CHANNEL_ID}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_AUTHN_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_TWINS_MQTT_URL: ${PD_TWINS_MQTT_URL}
    ports:
      - ${PD_TWINS_HTTP_PORT}:${PD_TWINS_HTTP_PORT}
    depends_on:
      - twins-db    

  nginx:
    image: nginx:1.16.0-alpine
    container_name: pandas-nginx
    restart: on-failure
    volumes:
      - ./nginx/nginx-key.conf:/etc/nginx/nginx.conf.template
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./nginx/snippets:/etc/nginx/snippets
      - ./ssl/authorization.js:/etc/nginx/authorization.js
      - ./ssl/certs/mainflux-server.crt:/etc/ssl/certs/mainflux-server.crt
      - ./ssl/certs/ca.crt:/etc/ssl/certs/ca.crt
      - ./ssl/certs/mainflux-server.key:/etc/ssl/private/mainflux-server.key
      - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - ${PD_NGINX_HTTP_PORT}:${PD_NGINX_HTTP_PORT}
      - ${PD_NGINX_SSL_PORT}:${PD_NGINX_SSL_PORT}
      - ${PD_NGINX_MQTT_PORT}:${PD_NGINX_MQTT_PORT}
      - ${PD_NGINX_MQTTS_PORT}:${PD_NGINX_MQTTS_PORT}
    env_file:
      - ../.env
    command: /entrypoint.sh
    depends_on:
      - things
      - users
      - mqtt-adapter
      - http-adapter
      - ws-adapter

  lbs-db:
    image: postgres:10.8-alpine
    container_name: pandas-lbs-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PD_LBS_DB_USER}
      POSTGRES_PASSWORD: ${PD_LBS_DB_PASS}
      POSTGRES_DB: ${PD_LBS_DB}
    volumes:
      - pandas-lbs-db-volume:/var/lib/postgresql/data

  lbs:
    image: pandas/pandas-lbs
    ports:
      - ${PD_LBS_HTTP_PORT}:${PD_LBS_HTTP_PORT}
    restart: always
    environment:
      PD_LBS_LOG_LEVEL: ${PD_LBS_LOG_LEVEL}
      PD_LBS_HTTP_PORT: ${PD_LBS_HTTP_PORT}
      PANDAS_DNS_SERVER: "docker-compose"
      PD_LBS_DB_HOST: lbs-db
      PD_LBS_DB_PORT: ${PD_LBS_DB_PORT}
      PD_LBS_DB_USER: ${PD_LBS_DB_USER}
      PD_LBS_DB_PASS: ${PD_LBS_DB_PASS}
      PD_LBS_DB: ${PD_LBS_DB}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_LBS_AUTH_HTTP_PORT: ${PD_LBS_AUTH_HTTP_PORT}
      PD_LBS_AUTH_GRPC_PORT: ${PD_LBS_AUTH_GRPC_PORT}
      PD_AUTH_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_LBS_SECRET: ${PD_LBS_SECRET}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
    depends_on:
      - lbs-db
  
  authz:
    image: pandas/pandas-authz:latest
    container_name: pandas-authz
    volumes:
      - ./users/emailer/templates/${PD_EMAIL_TEMPLATE}:/${PD_EMAIL_TEMPLATE}
    depends_on:
      - users-db
      - authn
    restart: on-failure
    environment:
      PD_USERS_LOG_LEVEL: ${PD_USERS_LOG_LEVEL}
      PD_USERS_DB_HOST: users-db
      PD_USERS_DB_PORT: ${PD_USERS_DB_PORT}
      PD_USERS_DB_USER: ${PD_USERS_DB_USER}
      PD_USERS_DB_PASS: ${PD_USERS_DB_PASS}
      PD_USERS_DB: ${PD_USERS_DB}
      PD_AUTHZ_HTTP_PORT: ${PD_AUTHZ_HTTP_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
      PD_EMAIL_DRIVER: ${PD_EMAIL_DRIVER}
      PD_EMAIL_HOST: ${PD_EMAIL_HOST}
      PD_EMAIL_PORT: ${PD_EMAIL_PORT}
      PD_EMAIL_USERNAME: ${PD_EMAIL_USERNAME}
      PD_EMAIL_PASSWORD: ${PD_EMAIL_PASSWORD}
      PD_EMAIL_FROM_ADDRESS: ${PD_EMAIL_FROM_ADDRESS}
      PD_EMAIL_FROM_NAME: ${PD_EMAIL_FROM_NAME}
      PD_EMAIL_TEMPLATE: ${PD_EMAIL_TEMPLATE}
      PD_TOKEN_RESET_ENDPOINT: ${PD_TOKEN_RESET_ENDPOINT}
      PD_AUTHN_URL: authn:${PD_AUTHN_GRPC_PORT}
    ports:
      - ${PD_AUTHZ_HTTP_PORT}:${PD_AUTHZ_HTTP_PORT}

  vms-db:
    image: postgres:10.8-alpine
    container_name: pandas-vms-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PD_VMS_DB_USER}
      POSTGRES_PASSWORD: ${PD_VMS_DB_USER}
      POSTGRES_DB: ${PD_VMS_DB}
    volumes:
      - pandas-vms-db-volume:/var/lib/postgresql/data

  vms-redis:
    image: redis:5.0-alpine
    container_name: pandas-vms-redis
    restart: on-failure
    volumes:
      - pandas-vms-redis-volume:/data

  vms:
    image: pandas/pandas-vms:latest
    container_name: pandas-vms
    depends_on:
      - vms-db
      - authn
    restart: on-failure
    environment:
      PD_VMS_LOG_LEVEL: ${PD_VMS_LOG_LEVEL}
      PD_VMS_HTTP_PORT: ${PD_VMS_HTTP_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_AUTHN_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_VMS_DB_HOST: vms-db
      PD_VMS_DB_PORT: ${PD_VMS_DB_PORT}
      PD_VMS_DB_USER: ${PD_VMS_DB_USER}
      PD_VMS_DB_PASS: ${PD_VMS_DB_PASS}
      PD_VMS_DB: ${PD_VMS_DB}
      PD_VMS_AUTH_HTTP_PORT: ${PD_VMS_AUTH_HTTP_PORT}
      PD_VMS_AUTH_GRPC_PORT: ${PD_VMS_AUTH_GRPC_PORT}
      PD_AUTH_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_VMS_SECRET: ${PD_VMS_SECRET}
      PD_VMS_CACHE_URL: vms-redis:${PD_REDIS_TCP_PORT}
      PD_VMS_ES_URL: es-redis:${PD_REDIS_TCP_PORT}
      PD_NATS_URL: ${PD_NATS_URL}
    ports:
      - ${PD_VMS_HTTP_PORT}:${PD_VMS_HTTP_PORT}
  
  pms-db:
    image: postgres:10.8-alpine
    container_name: pandas-pms-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PD_PMS_DB_USER}
      POSTGRES_PASSWORD: ${PD_PMS_DB_USER}
      POSTGRES_DB: ${PD_PMS_DB}
    volumes:
      - pandas-pms-db-volume:/var/lib/postgresql/data

  pms-redis:
    image: redis:5.0-alpine
    container_name: pandas-pms-redis
    restart: on-failure
    volumes:
      - pandas-pms-redis-volume:/data

  pms:
    image: pandas/pandas-pms:latest
    container_name: pandas-pms
    depends_on:
      - pms-db
      - authn
    restart: on-failure
    environment:
      PD_PMS_LOG_LEVEL: ${PD_PMS_LOG_LEVEL}
      PD_PMS_HTTP_PORT: ${PD_PMS_HTTP_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_AUTHN_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_PMS_DB_HOST: pms-db
      PD_PMS_DB_PORT: ${PD_PMS_DB_PORT}
      PD_PMS_DB_USER: ${PD_PMS_DB_USER}
      PD_PMS_DB_PASS: ${PD_PMS_DB_PASS}
      PD_PMS_DB: ${PD_PMS_DB}
      PD_PMS_AUTH_HTTP_PORT: ${PD_PMS_AUTH_HTTP_PORT}
      PD_PMS_AUTH_GRPC_PORT: ${PD_PMS_AUTH_GRPC_PORT}
      PD_AUTH_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_PMS_SECRET: ${PD_PMS_SECRET}
      PD_PMS_CACHE_URL: pms-redis:${PD_REDIS_TCP_PORT}
      PD_PMS_ES_URL: es-redis:${PD_REDIS_TCP_PORT}
      PD_NATS_URL: ${PD_NATS_URL}
    ports:
      - ${PD_PMS_HTTP_PORT}:${PD_PMS_HTTP_PORT}

  realms-db:
    image: postgres:10.8-alpine
    container_name: pandas-realms-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PD_REALMS_DB_USER}
      POSTGRES_PASSWORD: ${PD_REALMS_DB_USER}
      POSTGRES_DB: ${PD_REALMS_DB}
    volumes:
      - pandas-realms-db-volume:/var/lib/postgresql/data

  realms:
    image: pandas/pandas-realms:latest
    container_name: pandas-realms
    depends_on:
      - realms-db
      - authn
    restart: on-failure
    environment:
      PD_REALMS_LOG_LEVEL: ${PD_REALMS_LOG_LEVEL}
      PD_REALMS_HTTP_PORT: ${PD_REALMS_HTTP_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_AUTHN_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_REALMS_DB_HOST: realms-db
      PD_REALMS_DB_PORT: ${PD_REALMS_DB_PORT}
      PD_REALMS_DB_USER: ${PD_REALMS_DB_USER}
      PD_REALMS_DB_PASS: ${PD_REALMS_DB_PASS}
      PD_REALMS_DB: ${PD_REALMS_DB}
      PD_REALMS_AUTH_HTTP_PORT: ${PD_REALMS_AUTH_HTTP_PORT}
      PD_REALMS_AUTH_GRPC_PORT: ${PD_REALMS_AUTH_GRPC_PORT}
      PD_AUTH_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_REALMS_SECRET: ${PD_REALMS_SECRET}
    ports:
      - ${PD_REALMS_HTTP_PORT}:${PD_REALMS_HTTP_PORT}
  
  swagger:
    image: pandas/pandas-swagger:latest
    container_name: pandas-swagger

    restart: on-failure
    environment:
      PD_SWAGGER_LOG_LEVEL: ${PD_SWAGGER_LOG_LEVEL}
      PD_SWAGGER_HTTP_PORT: ${PD_SWAGGER_HTTP_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_AUTHN_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_SWAGGER_AUTH_HTTP_PORT: ${PD_SWAGGER_AUTH_HTTP_PORT}
      PD_SWAGGER_AUTH_GRPC_PORT: ${PD_SWAGGER_AUTH_GRPC_PORT}
      PD_AUTH_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_SWAGGER_SECRET: ${PD_SWAGGER_SECRET}
    ports:
      - ${PD_SWAGGER_HTTP_PORT}:${PD_SWAGGER_HTTP_PORT}

  kuiper-db:
    image: postgres:10.8-alpine
    container_name: pandas-kuiper-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${PD_KUIPER_DB_USER}
      POSTGRES_PASSWORD: ${PD_KUIPER_DB_USER}
      POSTGRES_DB: ${PD_KUIPER_DB}
    volumes:
      - pandas-realms-db-volume:/var/lib/postgresql/data

  kuiper:
    image: pandas/pandas-kuiper:latest
    container_name: pandas-kuiper
    depends_on:
      - kuiper-db
      - authn
    restart: on-failure
    environment:
      PD_KUIPER_LOG_LEVEL: ${PD_KUIPER_LOG_LEVEL}
      PD_KUIPER_HTTP_PORT: ${PD_KUIPER_HTTP_PORT}
      PD_JAEGER_URL: ${PD_JAEGER_URL}
      PD_NATS_URL: ${PD_NATS_URL}
      PD_AUTHN_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_KUIPER_DB_HOST: kuiper-db
      PD_KUIPER_DB_PORT: ${PD_KUIPER_DB_PORT}
      PD_KUIPER_DB_USER: ${PD_KUIPER_DB_USER}
      PD_KUIPER_DB_PASS: ${PD_KUIPER_DB_PASS}
      PD_KUIPER_DB: ${PD_KUIPER_DB}
      PD_KUIPER_AUTH_HTTP_PORT: ${PD_KUIPER_AUTH_HTTP_PORT}
      PD_KUIPER_AUTH_GRPC_PORT: ${PD_KUIPER_AUTH_GRPC_PORT}
      PD_AUTH_URL: authn:${PD_AUTHN_GRPC_PORT}
      PD_KUIPER_SECRET: ${PD_KUIPER_SECRET}
    ports:
      - ${PD_REALMS_HTTP_PORT}:${PD_KUIPER_HTTP_PORT}
  
 
