FROM pandas/pandas-base 

LABEL vendor=pandas
LABEL product=pandas

# ADD certs/* /etc/ssl/pandas
ADD pandas/cmd/cassandra-reader/bin/* /
RUN chmod 755 /main
RUN chmod 755 /dockerize

USER root

CMD ["/main"]
