FROM cloustone/pandas-base 

LABEL vendor=cloustone
LABEL product=pandas

# ADD certs/* /etc/ssl/pandas
ADD pandas/cmd/rulechain/bin/* /
RUN mkdir -p /rulechain/assets
ADD pandas/rulechain/assets/* /rulechain/assets/
RUN chmod 755 /main
RUN chmod 755 /dockerize

USER root

CMD ["/main"]
