FROM pandas/pandas-base 

LABEL vendor=pandas
LABEL product=pandas

# ADD certs/* /etc/ssl/pandas
ADD pandas/cmd/cli/bin/* /
ADD pandas/kuiper/etc /
ADD pandas/kuiper/plugins /
RUN chmod 755 /main
RUN chmod 755 /dockerize

USER root

CMD ["/main"]
